### ISSUE TITLE
Unable to set ffmpeg options

### ISSUE THREAD

**Issue by alicescfernandes** [kapoorlakshya/screen-recorder#100]
### Summary
I'm unable to set ffmpeg options
![image](https://user-images.githubusercontent.com/15971182/138482223-bc1effda-4c41-409f-955d-dfa76f065f8d.png)
Not sure if i'm doing correctly, but this seems not be working

```ruby
advanced = {  input: {depth: 16, video_size: '1280x720'} }
recorder = ScreenRecorder::Desktop.new(output: 'recording.webm', advanced: advanced)
recorder.start

```

### Debug Info
Please provide the following information for bug reports:

* Operating system - Linux (Docker)
* Ruby version: 2.5.1p57
* screen-recorder version: 1.6.0
* Recorder parameters -  {  input: {depth: 16, video_size: '1280x720'} }
* Recorder log (`ffmpeg.log`): * No logs are produced
* No logs are produced

### Expected Behavior
A screen recording with those parameters

### Actual Behavior
This error, and some weird files are being created

**Comment by kapoorlakshya** [comment]
@alicescfernandes Thanks for reporting this! I am able to reproduce it; will get a fix out very soon.

**Comment by kapoorlakshya** [comment]
@alicescfernandes Which version of `ffmpeg` are you using? I am using 4.2.4 and `depth` is not a recognized option. Using `sample_fmt` to set the depth works though:

```ruby
advanced = {  input: { sample_fmt: 16, video_size: '1280x720' } }
```

Can you give this a try and report back?

**Comment by kapoorlakshya** [comment]
@alicescfernandes Closing due to lack of response. Feel free to comment here if we need to reopen this.
