### ISSUE TITLE
ffmpeg is not gracefully killed when running on jenkins agent through ssh

### ISSUE THREAD

**Issue by waynemd** [kapoorlakshya/screen-recorder#103]
### Summary
ffmpeg is not gracefully killed when running on jenkins agent

### Debug Info
Please provide the following information for bug reports:

* Operating system - macOS 13.5
* Ruby version - 3.2.1
* screen-recorder version -1.6.0
* Recorder parameters - ScreenRecorder::Desktop.new(output: "#{@video_file}.mkv")
* Recorder log (`ffmpeg.log`) file as a gist or on pastebin.com.
* Set `ScreenRecorder.logger.level = Logger::DEBUG`, run the recorder, and share the
console output as a gist or on pastebin.com.

### Expected Behavior
ffmpeg should be gracefully killed and a recording file is produced

### Actual Behavior
ERROR - Forcefully killed ffmpeg. Recording failed!

[ffmpeg.log](https://github.com/kapoorlakshya/screen-recorder/files/12167098/ffmpeg.log)
[debugLog.txt](https://github.com/kapoorlakshya/screen-recorder/files/12167134/debugLog.txt)

I am suspecting the   `@process.io.stdin.puts 'q'`  line in the `stop_ffmpeg` cannot be run on the jenkins agent?  If I run the job on the jenkins master, it works.

**Comment by kapoorlakshya** [comment]
@waynemd Based on the error in `ffmpeg.log`, this appears to be the same issue as #88. Give this a try and let me know how it goes - https://github.com/kapoorlakshya/screen-recorder/issues/88#issuecomment-629139032

**Comment by waynemd** [comment]
@kapoorlakshya ,  I did try to enable all the related java and terminal processes for the screen recording in the privacy & security,   but it did not help

**Comment by kapoorlakshya** [comment]
@waynemd Got it. Is the Jenkins agent a mac mini or something with one or more monitors? I'm curious what `ffmpeg -f avfoundation -list_devices true -i ""` returns.

You should get a display number there. If it's not `1`, let's try passing it as a input ([instructions](https://github.com/kapoorlakshya/screen-recorder/wiki/Display-or-Input-Device-Selection)) and see if that works.

**Comment by waynemd** [comment]
@kapoorlakshya ,  I have tried adding the display number there but same error (input: '1:0' as the input parameter)
[debugLog.txt](https://github.com/kapoorlakshya/screen-recorder/files/12167134/debugLog.txt) has the return of that `ffmpeg -f avfoundation -list_devices true -i ""` at the top

**Comment by kapoorlakshya** [comment]
Can you try any other input to see if any of them work?

**Comment by waynemd** [comment]
None of the input parameter works if I run it on a jenkins agent.  Do you think the jenkins agent can handle the standard input interaction and respond appropriately to the input 'q'?  My jenkins agent is launched via SSH.

**Comment by kapoorlakshya** [comment]
Input handling doesn't appear to be the problem from what I can tell. It's ffmpeg itself failing to start screen capture, so I'm focusing on that part right now.

Can you share how this agent is set up? Is it a mac mini with monitors or an EC2 instance (or something similarly hosted by a 3rd party) that you access via SSH only?

**Comment by kapoorlakshya** [comment]
I just noticed in the main post you mentioned that it works fine on the Jenkins master, but not on the agent. I guess it could be a permission thing on the agent? I have only managed Linux and Windows boxes as Jenkins agent, so not familiar with macOS specific fixes/workarounds for this.

**Comment by kapoorlakshya** [comment]
Yeah, could be a permission thing still via SSH. You could try setting up a VNC session and then record it using ffmpeg. There are a few guides on Google, but I haven't tried it personally.

**Comment by waynemd** [comment]
VNC is not a viable solution for jenkins agent run.

**Comment by kapoorlakshya** [comment]
Did that workaround work?

**Comment by waynemd** [comment]
Yes.  The workaround is changing how you launch the jenkins agent

**Comment by kapoorlakshya** [comment]
@waynemd We good to close this issue?

**Comment by waynemd** [comment]
yes
