### ISSUE TITLE
No longer maitained? 

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#68]
Is this gem ffmpeg-screenrecorder no longer been maintained? I have been working with this gem. You supported few months back? 

What's the change? I can't record chrome screen so far. Can I record chrome screen if I use your new gem?

**Comment by kapoorlakshya** [comment]
That gem has been renamed to screen-recorder. You should update your project to use this one to receive long term updates.

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya 

Okay, thank you. Your gem was very very useful in my project. It perfectly records the video in firefox but it's not recording in chrome. Let's see whether I can do it this time. Thanks for such a good gem.

**Comment by kapoorlakshya** [comment]
That's good to hear :)

The same code should work for both browsers. Feel free to create an Issue if you run into problems.

**Comment by Rajagopalan-M** [comment]
Thank you. I will for sure

**Comment by Rajagopalan-M** [comment]
Hi, I don't know how to pass the option now.

this is my old coding

```
opts = {input: FFMPEG::WindowTitles.fetch('firefox').last,
                    output: File.expand_path("Output/Video/#{scenario}/#{testCase.first + '_' + testCase[1]}.mp4"),
                    framerate: 15}
            @recorder = FFMPEG::ScreenRecorder.new(opts)
```

New coding

```
@recorder = ScreenRecorder::Window.new(title: 'Mozilla Firefox', output: 'recording.mkv')
  @recorder.start
```

How to pass the option now?

**Comment by kapoorlakshya** [comment]
No need to pass options now. What you have is correct.

For Chrome, just use the title from the window when it launches. Last I checked it was  'Google Chrome'.

**Comment by Rajagopalan-M** [comment]
It's throwing the error. How are you finding the title? My WATIR is printing empty string for `@browser.title`

**Comment by kapoorlakshya** [comment]
Use `ScreenRecorder::Titles.fetch('chrome').last` right after you launch the browser. It'll give you the window title.

**Comment by Rajagopalan-M** [comment]
Hi, as you said, there is no need to pass the option now. It's great. But when It records Chrome, It records only black colour screen. I don't know why.

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M Please paste your code here. And the output from `ffmpeg -version`.

**Comment by Rajagopalan-M** [comment]
Here it is, 

https://gist.github.com/Rajagopalan-M/74fbc8cc7b63ff7b69e4009642b7f044

It records only black colour screen while I run in Chrome.

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M I was able to reproduce it using Chrome 74 on Windows 10. Other windows like RubyMine, Firefox and Task Manager work fine, so it's something specific to Chrome/Chromium based browsers. I reproduced this on Brave as well.

Can you please create a new Issue with all the info that it asks for? It'll be easier for me to track it that way. Thank you!

**Comment by Rajagopalan-M** [comment]
Ok thanks

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M Figured it out - Disable Harware Accelration in Chrome settings:

![image](https://user-images.githubusercontent.com/4314581/57350519-36d8b580-7113-11e9-8a89-c1c945fbc74f.png)

**Comment by Rajagopalan-M** [comment]
If I disable it works?

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M Yup, I just tested it in Chrome and Brave.

I have added an entry to the wiki for this - https://github.com/kapoorlakshya/screen-recorder/wiki/Black-Screen-on-Chrome

**Comment by Rajagopalan-M** [comment]
Great

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya  It works like a charm. Amazing , Amazing! Amazing! Thanks a lot.
