### ISSUE TITLE
Capture the second window

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#73]
I am using two monitor, One monitor my RubyMine would be opened and in my another monitor, Browser opens and runs on it. If I use desktop recorder, then it records both the monitor together, Can I have any way to record the second monitor only? I ask this because when I recorder firefox or chrome, it records only the first window, the second window if opens as a result of the click is not captured at all.

**Comment by kapoorlakshya** [comment]
> Can I have any way to record the second monitor only?

Check out the [wiki](https://github.com/kapoorlakshya/screen-recorder/wiki/Multi-monitor-Capture) for this.

> the second window if opens as a result of the click is not captured at all

Can you open the link in a new tab (same window frame) instead of a separate window? If not then capturing the Desktop for this particular case might be a better option.

**Comment by Rajagopalan-M** [comment]
That's great! Thanks. Tomorrow, I will check it out and let you know.

**Comment by kapoorlakshya** [comment]
Feel free to reopen this if you run into any problems.

**Comment by Rajagopalan-M** [comment]
Hi, sorry could not reply. I came to my home town. I will tell you once I
reach to my work. Thanks for the support.
