### ISSUE TITLE
Errno::EAGAIN: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#79]
Yesterday I was running 1000 testcases, it failed at 254 due to the following issue. Do you any clue as to why it happened? 

> Errno::EAGAIN: Resource temporarily unavailable - C:\ffmpeg\bin/ffprobe.EXE
> 
>   0) IDIT(KWI) Scenario1-EW EWPolicy_Test255
>      Failure/Error: @result = @obj.login.runTheTestCase @recorder
> 
>      Errno::EAGAIN:
>        Resource temporarily unavailable - C:\ffmpeg\bin/ffprobe.EXE
>    ./FrameWork/Browser/ExecuteTheTestCases.rb:33:in `runTheTestCase'
>     ./Ruby_test_spec.rb:206:in `block (5 levels) in <top (required)>'

I have created gist out of your ffmpeg.log file

https://gist.github.com/Rajagopalan-M/28221fbe74491adcd21aa0e5e3ffefdf

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M Based on the logs the recording (using `ffmpeg`) is successful, but `ffprobe` which is used to gather information about the video file is failing.

Does this error occur when you stop the recorder?

**Comment by Rajagopalan-M** [comment]
I am not sure about this. But I have raised another error for the new chrome which occurs when I stop the recorder. I completely convinced that this too occurs when I stop the recorder.

**Comment by kapoorlakshya** [comment]
I skimmed through the code and looks like `ffprobe` is used when we stop the recorder ([this line](https://github.com/kapoorlakshya/screen-recorder/blob/master/lib/screen-recorder/common.rb#L36)). I'll try to reproduce the issue and then update the stop method to rescue `Errno::EAGAIN: Resource temporarily unavailable` and retry up to 3 times.

**Comment by kapoorlakshya** [comment]
Thanks for reporting this! :)

**Comment by kapoorlakshya** [comment]
Hi @Rajagopalan-M, I have released v1.3.1 with a fix for this. Give it a try and let me know if you run into any other problems.

**Comment by Rajagopalan-M** [comment]
Okay

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
