### ISSUE TITLE
Broken Pipe line

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#82]
This new error is showing up now

```
Errno::EPIPE: Broken pipe

  0) StingRay(AGCS) Scenario6-WCPOLSEndorsedPolicy AGCSPolicyEndorsement_Test1
     Failure/Error: @process.io.stdin.close

     Errno::EPIPE:
       Broken pipe
```
This error is happening when I close the recorder  ` recorder.stop unless recorder.nil?`
Here is the ffmepg log

https://gist.github.com/Rajagopalan-M/fc7b4fe0de5cd2dca7936ba8c79321be

**Comment by kapoorlakshya** [comment]
Hey @Rajagopalan-M, the video recording itself is successful based on the `ffmpeg` log. I'll need the debug log from the gem to properly troubleshoot this.

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya Okay, this error is not happening right now. If it happens again, I will let you know. And I use your recorder while I do parallel run, it is not recording properly. Video records the first page and stops there and after few minutes it catches other pages. This recorder can't be used for parallel run?

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M I have not tested the gem for parallel test executions.

> Video records the first page and stops there and after few minutes it catches other pages.

That's probably because `ffmpeg` is probably focusing on the new window with the same title. It's just something that `ffmpeg` is designed to do I guess. I can't think of a solution that I can implement in the gem to change that behavior.

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya 

Sure, thanks.

**Comment by kapoorlakshya** [comment]
I'm closing this for now, but feel free to revive it when you have more information.
