### ISSUE TITLE
Error when I try to install screenrecorder

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#85]
When I try install screenrecorder, it is throwing the following error, My ruby version is 2.6.5
```
Gem::ConflictError:
  Unable to activate screen-recorder-1.3.1, because childprocess-1.0.1 conflicts with childprocess (~> 3.0)
# SequencialRun.rb:9:in `<top (required)>'
# ./Ruby_test_spec.rb:52:in `load'
# ./Ruby_test_spec.rb:52:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- screen-recorder
#   SequencialRun.rb:9:in `<top (required)>'
No examples found.

```

**Comment by kapoorlakshya** [comment]
Do you have a version for `childprocess` gem defined (locked) in your `Gemfile`? A simple `bundle update` should work otherwise.

**Comment by Rajagopalan-M** [comment]
I don't have any gem file here, I install gem using the command `gem install screen-recorder` and it gives me the above error, I installed childprocess-1.0.1 after uninstalling 3.0 but it still throws the error.

**Comment by kapoorlakshya** [comment]
`childprocess` 1.x is no longer needed. Try this:

1. Uninstall all versions of `childprocess` and `screen-recorder`
2. Run `gem install screen-recorder`. This will get you the latest version.

**Comment by Rajagopalan-M** [comment]
Hi, It's getting installed.

![image](https://user-images.githubusercontent.com/31696622/73048929-c213fa00-3ea0-11ea-8e2d-2c0bcf923f08.png)

But while I am running, it's throwing the following error.


```
Gem::ConflictError:
  Unable to activate screen-recorder-1.3.1, because childprocess-1.0.1 conflicts with childprocess (~> 3.0)
# SequencialRun.rb:9:in `<top (required)>'
# ./Ruby_test_spec.rb:52:in `load'
# ./Ruby_test_spec.rb:52:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- screen-recorder
#   SequencialRun.rb:9:in `<top (required)>'
No examples found.

```

**Comment by kapoorlakshya** [comment]
What does the following command return?

```
gem dependency childprocess --reverse-dependencies
```

**Comment by Rajagopalan-M** [comment]
It returns
![image](https://user-images.githubusercontent.com/31696622/73049656-3780ca00-3ea3-11ea-9fa0-1a0895054033.png)

**Comment by kapoorlakshya** [comment]
Oh it's because you're using `selenium-webdriver` 3.142.3 which still requires `childprocess` < v2.

I'll relax the `childprocess` requirement to be `>= 1.0, < 4.0` in the next `screen-recorder` release, but I would recommend using the latest Selenium (and `childprocess`) release if you can.

**Comment by Rajagopalan-M** [comment]
Recent version of selenium has this problem and that's why I couldn't go there

https://github.com/SeleniumHQ/selenium/issues/7917
