### ISSUE TITLE
How to redirect the log into the required folder? 

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#87]
There is a file named ffmepg.log is created in my root folder but I want to move this file into another folder, can I set up the path for this file like we can set up the path for watir.log file as `Watir.logger.output = 'AppData/Logs/watir.log'` ?

**Comment by kapoorlakshya** [comment]
Yes, see the log parameter in the Advanced Options section of the readme.

**Comment by kapoorlakshya** [comment]
Oops... Accidentally closed this. I'll close this ticket once you confirm it works.

**Comment by Rajagopalan-M** [comment]
You have given this

```
You can configure the logging level of the gem to troubleshoot problems:

ScreenRecorder.logger.level = :DEBUG

Also, refer to the ffmpeg.log file for details.
```
But I am asking how to set up the path for ffmpeg.log file?

**Comment by kapoorlakshya** [comment]
That's the wrong section. Look one section above titled "Advanced Options" - https://github.com/kapoorlakshya/screen-recorder/blob/master/README.md#advanced-options

Specifically the `log` key in the example.

**Comment by Rajagopalan-M** [comment]
So I can write this

```
advanced = {

  log:      'recorder.log',

}
```

**Comment by Rajagopalan-M** [comment]
Beautiful, it works fine. Thanks. You close this issue now.

**Comment by kapoorlakshya** [comment]
Great!
