### ISSUE TITLE
Current timestamp of recording

### ISSUE THREAD

**Issue by phil-l-brockwell** [kapoorlakshya/screen-recorder#92]
### Summary
A instance method on the ScreenRecorder::Desktop instance which returns the current timestamp of the recording in process.

I'm not that familiar with ffmpeg so I'm not sure how easy this would be to implement, however, with a nod in the right direction I would be happy to contribute and open a PR.

**Comment by kapoorlakshya** [comment]
@phil-l-brockwell I am not seeing a way to retrieve the current timestamp from `ffmpeg` itself for the recording in process. However, you could start your own timer right after starting the recorder and then use that to get somewhat accurate timestamps. Check out the [`stop_watch`](https://github.com/danielpclark/stop_watch) gem for this. Alternatively, there is a way to [print the timestamp on the video](https://superuser.com/questions/1020102/adding-a-timestamp-on-frames-captured-using-ffmpeg) itself. 

By the way, what's the use case for this feature?

**Comment by phil-l-brockwell** [comment]
Thanks for getting back to me @kapoorlakshya 

I'm recording a video and noting specific points during the video then retrospectively adding audio etc.

I have tried to use a timer as you suggested but it isn't accurate enough and putting the timestamp on the finished video wouldn't fit the use case. I think their is some lag in between the ffmpeg process beginning and when recording begins.

**Comment by kapoorlakshya** [comment]
> I'm recording a video and noting specific points during the video then retrospectively adding audio etc.

Is this audio an external track, like music or voice-over, or audio out from the system? Asking to see if we can capture audio in the recording ([instructions](https://github.com/kapoorlakshya/screen-recorder#capture-audio])).


> I think their is some lag in between the ffmpeg process beginning and when recording begins.

Yeah, `ffmpeg` takes 1-1.5 seconds on a cold start, which why I had to hardcode a 1.5s delay in [`#start`](https://github.com/kapoorlakshya/screen-recorder/blob/master/lib/screen-recorder/common.rb#L74). So if you were to start the timer after calling `#start`, it should give a bit more accurate timestamps than if you were to start the time before.

**Comment by phil-l-brockwell** [comment]
It's an external track, and at some point I want to make it variable/interchangeable so it has to be done after the filming and accurately.

I did notice the 1.5s delay actually and tried to compensate by adding a delay to the timer, this definitely produces a more accurate result but not precise enough. I wonder if their is a way to ensure the delay of starting ffmpeg is always a fixed time?

**Comment by kapoorlakshya** [comment]
Ah, got it!

>  I wonder if their is a way to ensure the delay of starting ffmpeg is always a fixed time?

Hmm... I am not sure if that's possible to control in the gem code since the delay is from `ffmpeg` itself. My hard coded delay is just a naive way to make sure the next lines of code (after initializing the recorder) are only executed once ffmpeg is ready and has begun recording.

This is an interesting use case that I had not consider when creating this gem. The only use case I had in mind was to record automated UI test cases using Selenium. I'll have to think a little more and experiment to figure out how we can make this possible. Please don't have any expectations because it's completely possible that there isn't a good way to get 100% accurate timestamps when using this gem, but we'll see.

If you don't mind me asking, what are you filming/recording?

**Comment by phil-l-brockwell** [comment]
Anytime you can spend is massively appreciated, you've been really helpful this far, as I said previously, I will be happy to work on a solution/pr I just need a little help in the right direction.

Unfortunately I'm working confidentially with a client and I can't really go into any more detail, but I will keep you posted

**Comment by kapoorlakshya** [comment]
> I will be happy to work on a solution/pr I just need a little help in the right direction.

The only approach I can think of right now is to embed the [`stop_watch`](https://github.com/danielpclark/stop_watch) gem and expose the `StopWatch::Timer` object (ex: `@recorder.timer`) and call `timer.mark` in [`#start_ffmpeg`](https://github.com/kapoorlakshya/screen-recorder/blob/master/lib/screen-recorder/common.rb#L72) right before and after spawning the `ffmpeg` process. This will record the time right when ffmpeg is initialized and then again after the 1.5s wait when the recording starts. This way you'll have a window of ~1.5s to play with to get your audio timing right. And you can always call `@recorder.timer.mark` to mark additional timestamps during the recording (see usage [examples](https://github.com/danielpclark/stop_watch#usage)).

I'm flexible on which gem we use for this. If you have a better one that suits your needs, I'd be happy to go with itas long as it doesn't have too many dependencies.

> Unfortunately I'm working confidentially with a client and I can't really go into any more detail, but I will keep you posted

Totally understandable. I was just curious to know what this gem is being used for in general.

**Comment by phil-l-brockwell** [comment]
Interesting idea, I'm not sure if I fully understand it though. So you would use the two timestamps to work out the lag between calling ffmpeg and it actually starting it then subtract this from any subsequent timestamps?

**Comment by kapoorlakshya** [comment]
@phil-l-brockwell Yeah, that's what I am thinking.

Another idea, based on printing the timestamps in the video, is to:

1.  Add a white/black bar at the bottom of the video using the `pad` filter ([instructions](https://superuser.com/questions/690021/video-padding-using-ffmpeg/690211))
2. Print the timestamp in the bar using the `x,y` coordinates of the `drawtext` filter ([instructions](https://superuser.com/questions/1020102/adding-a-timestamp-on-frames-captured-using-ffmpeg))
3. Go through the video and note the timestamps you need
4. Then during post-processing, crop out the bar with the timestamps and add audio using timestamps from step 3

Steps 1-2 should be doable using the `advanced` parameter, and this will yield precise timestamps from `ffmpeg` itself.

**Comment by kapoorlakshya** [comment]
Hey @phil-l-brockwell, any updates? If not then I would like to close this ticket.
