### ISSUE TITLE
TaskBar is getting recorded while I am doing Desktop recording.

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/screen-recorder#93]
When I choose the record the Desktop, recording video includes the Task Bar as well. Is there anyway to exclude the task bar?

**Comment by kapoorlakshya** [comment]
The `desktop` mode records everything that is displayed on your monitor, including the taskbar. Try cropping out the taskbar by setting the `offset_x` and `offset_y` in the `advanced` configs. See examples [here](https://github.com/kapoorlakshya/screen-recorder/wiki/Multi-monitor-Capture#microsoft-windows-gdigrab) and [here](https://video.stackexchange.com/questions/22000/how-can-i-crop-part-of-a-video-while-recording-from-desktop-in-real-time-using-f).

**Comment by Rajagopalan-M** [comment]
Okay, thanks.
