### ISSUE TITLE
Possible issue with recording on remote desktop with no display?

### ISSUE THREAD

**Issue by nerrante** [kapoorlakshya/screen-recorder#95]
### Summary
I am guessing to the cause of the problem but I could be wrong. I'm trying to record my automated testing using your screen-recorder gem. It works awesome when I run it locally on my computer.  But I run my test runs normally on a remote machine (by ssh-ing in) that has no display. I'm wondering if the "no display" is causing my issue and perhaps there is some advanced setting I can change for FFmpeg that will make it work. Am hoping you can help!  

My test framework is Cucumber ruby.

### Debug Info
* Operating system - Microsoft Windows 10
* Ruby version:  2.6.5p114 (2019-10-01 revision 67812) [i386-mingw32]
* screen-recorder version: 1.4.0
* Recorder parameters
Here is the recorder related code in hooks.rb
```
Before do |scenario|
     if ENV["debug_run"] == 'yes'
          @recording_name = scenario.name.gsub(/\s/, "-").downcase + ".mp4"
     end
end

After do |scenario|
  @recorder.stop if ENV["debug_run"] == "yes"
  if scenario.failed?
     **some code**
  else
    @recorder.discard if ENV["debug_run"] == 'yes'
  end
end
```

Here's the recorder related code I have in my login method (so that I can be sure window is opened before the recorder is started:
```
  def login1(username, password)
    visit(ENV["HOMEPAGE"])
    if ENV['debug_run'] == 'yes'
	advanced = {
	log:      'recorder.log',
  loglevel: 'level+debug',
}
      window_title =  ScreenRecorder::Titles.fetch("Chrome").first
      @recorder = ScreenRecorder::Window.new(title: window_title, output: "#{@recording_name}", advanced: advanced)
      @recorder.start
    end
  end
```

* Recorder log (`ffmpeg.log`) file as a gist or on pastebin.com.
I turned debug on for this log as well:
https://pastebin.com/ZJf0nR74

* Set `ScreenRecorder.logger.level = Logger::DEBUG`, run the recorder, and share the
console output as a gist or on pastebin.com.
Here's the relevant part of the log:
https://pastebin.com/JcJy8MGE

### Expected Behavior
Screen Recorder successfully saves video.

### Actual Behavior
Error is received:
Failed to start ffmpeg. Reason: [info] Output #0, mp4, to 'edit-taxonomy-box-in-studbook-with-valid-data.mp4':
 [error] Output file #0 does not contain any stream
 (FFMPEG::Error)

**Comment by kapoorlakshya** [comment]
@nerrante You mentioned ssh-ing in to run the tests, but the OS listed in the debug info is Windows. Are you using WSL or OpenSSH on Windows to ssh in or are the tests running on Linux?

Just in case, if the error is happening on Linux or WSL, you can use [xvfb](https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml) to spin up a virtual screen and then follow the instructions in this [wiki](https://github.com/kapoorlakshya/screen-recorder/wiki/xvfb-or-headless-Capture) to record it.

**Comment by nerrante** [comment]
Hi @kapoorlakshya , the tests are running on Windows. It has Cygwin installed on it, which gives it a Unix-like layer to give access to more tools and functionality (including SSH).

**Comment by kapoorlakshya** [comment]
Ah okay. Well, cygwin not directly supported, but if you can get xvfb to run then that should allow you to record the video.

**Comment by nerrante** [comment]
I will give that a try, thanks @kapoorlakshya!
