### ISSUE TITLE
Relax os gem version specificity from patch to minor

### ISSUE THREAD

**Issue by hlascelles** [kapoorlakshya/screen-recorder#96]
### Summary
The version specification for `os` is quite tight: `spec.add_runtime_dependency 'os', '~> 1.0.0'`
Can we relax it to `spec.add_runtime_dependency 'os', '~> 1.0'`?
We have other projects that have gems that use `1.1.x`.

**Comment by kapoorlakshya** [comment]
@hlascelles Sure, that should work. Would you mind submitting a PR?

**Comment by hlascelles** [comment]
Yep, sure thing!

**Comment by hlascelles** [comment]
Opened.

**Comment by kapoorlakshya** [comment]
v1.5.0 has been released!
